name: Build RDSTester (x86 Debug & Release)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Debug and Release (x86)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Debug | x86
      run: msbuild RDSTester.sln /p:Configuration=Debug /p:Platform=x86 /p:IncludePath="ttf_to_f16\\libs\\freetype\\include;$(IncludePath)"

    - name: Copy freetype.dll and freetype.lib to Debug
      run: |
        mkdir Debug
        copy "ttf_to_f16\\libs\\freetype\\release dll\\win32\\freetype.dll" Debug\\
        copy "ttf_to_f16\\libs\\freetype\\release dll\\win32\\freetype.lib" Debug\\

    - name: Upload Debug Executable, DLL and LIB
      uses: actions/upload-artifact@v4
      with:
        name: RDSTester-Debug-x86
        path: |
          **/Debug/*.exe
          **/Debug/freetype.dll
          **/Debug/freetype.lib

    - name: Build Release | x86
      run: msbuild RDSTester.sln /p:Configuration=Release /p:Platform=x86 /p:IncludePath="ttf_to_f16\\libs\\freetype\\include;$(IncludePath)"

    - name: Copy freetype.dll and freetype.lib to Release
      run: |
        mkdir Release
        copy "ttf_to_f16\\libs\\freetype\\release dll\\win32\\freetype.dll" Release\\
        copy "ttf_to_f16\\libs\\freetype\\release dll\\win32\\freetype.lib" Release\\

    - name: Upload Release Executable, DLL and LIB
      uses: actions/upload-artifact@v4
      with:
        name: RDSTester-Release-x86
        path: |
          **/Release/*.exe
          **/Release/freetype.dll
          **/Release/freetype.lib
